<?xml version='1.0'?>

<robot name="skid_steer_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find skid_steer_bot)/urdf/skid_steer_bot.gazebo" />

  <!-- Scale the robot size to fit the environment -->
  <xacro:property name="scale" value="1.0" />

  <!-- Length along X-axis, Width along Y-axis, Height along Z-axis -->
  <xacro:property name="mower_width" value="${scale * 0.46}" />
  <xacro:property name="mower_length" value="${scale * 0.46}" />
  <xacro:property name="mower_height" value="${scale * 0.3}" />
  <xacro:property name="mower_mass" value="${scale * 10}" />

  <xacro:property name="base_x_offset" value="0" />

  <!-- inertia = 1/12*m(h^2+d^2) -->
  <xacro:property name="height_2" value="${mower_height * mower_height}" />
  <xacro:property name="width_2" value="${mower_width * mower_width}" />
  <xacro:property name="length_2" value="${mower_length * mower_length}" />
  <xacro:property name="mower_inertia_xx" value="${mower_mass/12.0 * (height_2 + width_2)}" />
  <xacro:property name="mower_inertia_yy" value="${mower_mass/12.0 * (height_2 + length_2)}" />
  <xacro:property name="mower_inertia_zz" value="${mower_mass/12.0 * (width_2 + length_2)}" />
  <xacro:property name="mower_i_x_pos" value="${base_x_offset}" />
  <xacro:property name="mower_i_z_pos" value="${mower_height/3.0}" />

  <xacro:property name="mower_frame_width" value="${mower_width - 2.1 * wheel_length}" />
  <xacro:property name="mower_frame_length" value="${mower_length*1.2}" />
  <xacro:property name="mower_frame_height" value="${mower_height/4.0}" />

  <xacro:property name="hardware_width" value="${mower_width/2.0}" />
  <xacro:property name="hardware_length" value="${mower_length/2.0}" />
  <xacro:property name="hardware_height" value="${mower_height/2.0}" />
  <xacro:property name="hardware_z_offset" value="${hardware_height/2.0}" />

  <xacro:property name="wheel_length" value="${scale * 0.05}" />
  <xacro:property name="wheel_radius" value="${scale * 0.08}" />
  <xacro:property name="wheel_mass" value="${scale * 1}" />
  <xacro:property name="wheel_inertia" value="${scale * 1e-3}" />
  <xacro:property name="wheel_x_offset" value="${base_x_offset + mower_length/2.0}" />
  <xacro:property name="wheel_y_offset" value="${mower_width/2.0 - wheel_length/2.0}" />

  <xacro:property name="camerra_width" value="0.05" />
  <xacro:property name="camerra_length" value="0.05" />
  <xacro:property name="camerra_height" value="0.05" />
  <xacro:property name="camerra_x_offset" value="${hardware_length/2.0 + base_x_offset - camerra_length/2.0 + 0.001}" />
  <xacro:property name="camerra_z_offset" value="${hardware_height - camerra_height/2.0 + 0.001}" />

  <xacro:property name="laser_width" value="0.1" />
  <xacro:property name="laser_length" value="0.1" />
  <xacro:property name="laser_height" value="0.1" />
  <xacro:property name="laser_x_offset" value="${base_x_offset}" />
  <xacro:property name="laser_z_offset" value="${hardware_height + 0.025}" />

  <xacro:property name="wheel_kp" value="1000000.0" />
  <xacro:property name="wheel_kd" value="100.0" />
  <xacro:property name="wheel_mu1" value="1" />
  <xacro:property name="wheel_mu2" value="1" />
  <xacro:property name="wheel_slip1" value="0.5" />
  <xacro:property name="wheel_slip2" value="0" />


  <link name="robot_footprint"></link>

  <joint name="robot_footprint_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="robot_footprint" />
    <child link="chassis" />
  </joint>

  <link name='chassis'>
    <inertial>
      <mass value="${mower_mass}"/>
      <origin xyz="${mower_i_x_pos} 0 ${mower_i_z_pos}" rpy=" 0 0 0"/>
      <inertia
          ixx="${mower_inertia_xx}" ixy="0" ixz="0"
          iyy="${mower_inertia_yy}" iyz="0"
          izz="${mower_inertia_zz}" />
    </inertial>

    <collision>
      <origin xyz="${base_x_offset} 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${mower_frame_length} ${mower_frame_width} ${mower_frame_height}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="${base_x_offset} 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${mower_frame_length} ${mower_frame_width} ${mower_frame_height}"/>
      </geometry>
    </visual>

    <!-- blade frame -->
    <collision>
      <origin xyz="${base_x_offset} 0 0" rpy=" 0 0 0"/>
      <geometry>
        <cylinder radius="${mower_width/2.0}" length="${mower_frame_height}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="${base_x_offset} 0 0" rpy=" 0 0 0"/>
      <geometry>
        <cylinder radius="${mower_width/2.0}" length="${mower_frame_height}"/>
      </geometry>
    </visual>

    <!-- hardware frame -->
    <collision>
      <origin xyz="${base_x_offset} 0 ${hardware_z_offset}" rpy=" 0 0 0"/>
      <geometry>
        <box size="${hardware_length} ${hardware_width} ${hardware_height}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="${base_x_offset} 0 ${hardware_z_offset}" rpy=" 0 0 0"/>
      <geometry>
        <box size="${hardware_length} ${hardware_width} ${hardware_height}"/>
      </geometry>
    </visual>

  </link>


  <!-- left back wheel -->
  <joint type="continuous" name="left_back_wheel_hinge">
    <origin xyz="-${wheel_x_offset} ${wheel_y_offset} 0" rpy="0 0 0"/>
    <child link="left_back_wheel"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>

  <link name="left_back_wheel">
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin xyz="0.0 0 0" rpy=" 0 1.5707 1.5707"/>
      <inertia
        ixx="${wheel_inertia}" ixy="0" ixz="0"
        iyy="${wheel_inertia}" iyz="0"
        izz="${wheel_inertia}" />
    </inertial>
    <collision name="left_back_wheel_collision">
      <origin xyz="0 0 0" rpy=" 0 1.5707 1.5707"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
      <surface>
        <friction>
          <fdir1>1 0 0</fdir1>
          <kp>${wheel_kp}</kp> <!-- kp and kd for rubber -->
          <kd>${wheel_kd}</kd>
          <mu>${wheel_mu1}</mu>
          <mu2>${wheel_mu2}</mu2>
          <slip1>${wheel_slip1}</slip1>
          <slip2>${wheel_slip2}</slip2>
        </friction>
      </surface>
    </collision>
    <visual name="left_back_wheel_visual">
      <origin xyz="0 0 0" rpy=" 0 1.5707 1.5707"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </visual>
  </link>

  <!-- right back wheel -->
  <joint type="continuous" name="right_back_wheel_hinge">
    <origin xyz="-${wheel_x_offset} -${wheel_y_offset} 0" rpy="0 0 0"/>
    <child link="right_back_wheel"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>

  <link name="right_back_wheel">
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin xyz="0.0 0 0" rpy=" 0 1.5707 1.5707"/>
      <inertia
          ixx="${wheel_inertia}" ixy="0" ixz="0"
          iyy="${wheel_inertia}" iyz="0"
          izz="${wheel_inertia}" />
    </inertial>
    <collision name="right_back_wheel_collision">
      <origin xyz="0 0 0" rpy=" 0 1.5707 1.5707"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
      <surface>
        <friction>
          <fdir1>1 0 0</fdir1>
          <kp>${wheel_kp}</kp> <!-- kp and kd for rubber -->
          <kd>${wheel_kd}</kd>
          <mu>${wheel_mu1}</mu>
          <mu2>${wheel_mu2}</mu2>
          <slip1>${wheel_slip1}</slip1>
          <slip2>${wheel_slip2}</slip2>
        </friction>
      </surface>
    </collision>
    <visual name="right_back_wheel_visual">
      <origin xyz="0 0 0" rpy=" 0 1.5707 1.5707"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </visual>
  </link>

  <!-- left front wheel -->
  <joint type="continuous" name="left_front_wheel_hinge">
    <origin xyz="${wheel_x_offset} ${wheel_y_offset} 0" rpy="0 0 0"/>
    <child link="left_front_wheel"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>

  <link name="left_front_wheel">
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin xyz="0.0 0 0" rpy=" 0 1.5707 1.5707"/>
      <inertia
        ixx="${wheel_inertia}" ixy="0" ixz="0"
        iyy="${wheel_inertia}" iyz="0"
        izz="${wheel_inertia}" />
    </inertial>
    <collision name="left_front_wheel_collision">
      <origin xyz="0 0 0" rpy=" 0 1.5707 1.5707"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
      <surface>
        <friction>
          <fdir1>1 0 0</fdir1>
          <kp>${wheel_kp}</kp> <!-- kp and kd for rubber -->
          <kd>${wheel_kd}</kd>
          <mu>${wheel_mu1}</mu>
          <mu2>${wheel_mu2}</mu2>
          <slip1>${wheel_slip1}</slip1>
          <slip2>${wheel_slip2}</slip2>
        </friction>
      </surface>
    </collision>
    <visual name="left_front_wheel_visual">
      <origin xyz="0 0 0" rpy=" 0 1.5707 1.5707"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </visual>
  </link>

  <!-- right front wheel -->
  <joint type="continuous" name="right_front_wheel_hinge">
    <origin xyz="${wheel_x_offset} -${wheel_y_offset} 0" rpy="0 0 0"/>
    <child link="right_front_wheel"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>

  <link name="right_front_wheel">
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin xyz="0.0 0 0" rpy=" 0 1.5707 1.5707"/>
      <inertia
          ixx="${wheel_inertia}" ixy="0" ixz="0"
          iyy="${wheel_inertia}" iyz="0"
          izz="${wheel_inertia}" />
    </inertial>
    <collision name="right_front_wheel_collision">
      <origin xyz="0 0 0" rpy=" 0 1.5707 1.5707"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
      <surface>
        <friction>
          <fdir1>1 0 0</fdir1>
          <kp>${wheel_kp}</kp> <!-- kp and kd for rubber -->
          <kd>${wheel_kd}</kd>
          <mu>${wheel_mu1}</mu>
          <mu2>${wheel_mu2}</mu2>
          <slip1>${wheel_slip1}</slip1>
          <slip2>${wheel_slip2}</slip2>
        </friction>
      </surface>
    </collision>
    <visual name="right_front_wheel_visual">
      <origin xyz="0 0 0" rpy=" 0 1.5707 1.5707"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </visual>
  </link>


  <link name='camera'>
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <inertia
          ixx="1e-6" ixy="0" ixz="0"
          iyy="1e-6" iyz="0"
          izz="1e-6"/>
    </inertial>
    <collision name='camera_collision'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${camerra_length} ${camerra_width} ${camerra_height}"/>
      </geometry>
    </collision>
    <visual name='camera_visual'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${camerra_length} ${camerra_width} ${camerra_height}"/>
      </geometry>
    </visual>
  </link>

  <joint type="fixed" name="camera_joint">
    <origin xyz="${camerra_x_offset} 0 ${camerra_z_offset}" rpy="0 0 0"/>
    <child link="camera"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>


  <link name='hokuyo'>
    <pose>0 0 0 0 0 0</pose>
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <inertia
          ixx="1e-6" ixy="0" ixz="0"
          iyy="1e-6" iyz="0"
          izz="1e-6" />
    </inertial>
    <collision name='hokuyo_collision'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${laser_length} ${laser_width} ${laser_height}"/>
      </geometry>
    </collision>
    <visual name='hokuyo_visual'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <mesh filename="package://skid_steer_bot/meshes/hokuyo.dae"/>
      </geometry>
    </visual>
  </link>

  <joint type="fixed" name="hokuyo_joint">
    <origin xyz="${laser_x_offset} 0 ${laser_z_offset}" rpy="0 0 0"/>
    <child link="hokuyo"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>

</robot>
